### ISSUE TITLE
[Question] Release schedule for llava-plus-weight? Is it still based on vicuna-v0-7b?

### ISSUE THREAD

**Issue by yhyu13** [LLaVA-VL/LLaVA-Plus-Codebase#1]
### Question

Hi,

https://github.com/haotian-liu/LLaVA/blob/main/docs/MODEL_ZOO.md 

It seems the weight for llava-plus has been released yet. Is there a schedule for model releasing?

Also, is llava-plus still based on vicuna-v0 series?

**Comment by SlongLiu** [comment]
We are working on releasing the pre-trained checkpoints.

Our model is the same as LLaVA, with different training data. Hence yes, we developed based on the vicuna series

**Comment by yhyu13** [comment]
Awesome, looking forward testing out this amazing work soon~

**Comment by SlongLiu** [comment]
> Awesome, looking forward testing out this amazing work soon~
> 
> I guess this is 1st open source multi-modal model with function calling abilities like recent release of GPTs?
> 
> All showcases in the demo pages works just as promised, the img description, seg and bb abilties work as charm.
> 
> Do you guys have any plans for conqure sound && motion picture modalities as well any time soon?

Thanks for your interested questions. We will take the suggestions into account, but have no guarantee about the progresses. Welcome to train your own models, like we do, for different modalities & scenarios!

**Comment by yhyu13** [comment]
@SlongLiu 

Seems video-image pair modality is solved here https://arxiv.org/abs//2311.10122
https://github.com/PKU-YuanGroup/Video-LLaVA
