### ISSUE TITLE
Unable to open the demo.

### ISSUE THREAD

**Issue by huxian0402** [LLaVA-VL/LLaVA-Plus-Codebase#6]
@haotian-liu @ChunyuanLI @SlongLiu  great work，but can't nable to open the demo. https://llavaplus.ngrok.io/, Can you provide a new demo link that works properly?

**Comment by SlongLiu** [comment]
Thanks for the question. There are some problems with our host machine, we are rebooting it.

**Comment by huxian0402** [comment]
> Thanks for the question. There are some problems with our host machine, we are rebooting it.

thanks, and when will it be fixed approximately?

**Comment by SlongLiu** [comment]
> Author

Now it works! have a try at https://llavaplus.ngrok.io/

**Comment by geoexploring** [comment]
@SlongLiu , The demo still doesn't work

**Comment by jaebbb** [comment]
@SlongLiu, not open yet. when will it work?

**Comment by Redtides0** [comment]
still doesn't work  :-(

**Comment by PHOENIXFURY007** [comment]
The demo page doesn't work

**Comment by giancohs** [comment]
Still doesn't work :/

**Comment by cutelove** [comment]
@SlongLiu  Thanks for your great work, but the demo doesn't work, is this project pended?
